import datetime
# import hashlib
from app import db, app, request, jwt
from flask import Flask, request,jsonify
from flask_jwt_extended import create_access_token, JWTManager, get_jwt_identity, jwt_required, current_user
from sqlalchemy import asc, desc
from extras.utilities import *
from models.Effortsdistribution import *
from sqlalchemy import func
import math
# import shutil


#List of all Project Category
@app.route("/data/load",methods=["GET"])
def insert_data():
    item=[
        {
            'e_dis_id': 1,
            'phase': "Sprint Planning",
            'stlc_name': "Sprint Planning & Strategizing",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 5,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 2,
            'phase': "In-Sprint Design",
            'stlc_name': "In Sprint Test Design (Manual)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 15,
            'override_breakup': 15,
            'status': 1,
        },
        {
            'e_dis_id': 3,
            'phase': "In-Sprint Design",
            'stlc_name': "In Sprint Test Design (Automation)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 30,
            'override_breakup': 30,
            'status': 1,
        },
        {
            'e_dis_id': 4,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Environment Management)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 2,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 5,
            'phase': "In-Sprint Execution",
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 2,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 6,
            'phase': "In-Sprint Design",
            'stlc_name': "In-Sprint Test Design (Regression Maintenance)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 5,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 7,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Functional)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 21,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 8,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 5,
            'override_breakup': 5,
            'status': 1,
        },
        {
            'e_dis_id': 9,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 5,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 10,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Others)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 5,
            'override_breakup': 20,
            'status': 1,
        },
        {
            'e_dis_id': 11,
            'phase': "In-Sprint Execution",
            'stlc_name': "Test Execution (Defect Management)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 3,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 12,
            'phase': "Sprint Review & Retrospection",
            'stlc_name': "Sprint Review & Retrospection",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': 2,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 13,
            'phase': "Sprint Planning",
            'stlc_name': "Sprint Planning & Strategizing",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 3,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 14,
            'phase': "In-Sprint Design",
            'stlc_name': "In Sprint Test Design (Manual)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 15,
            'override_breakup': 15,
            'status': 1,
        },
        {
            'e_dis_id': 15,
            'phase': "In-Sprint Design",
            'stlc_name': "In Sprint Test Design (Automation)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 22,
            'override_breakup': 30,
            'status': 1,
        },
        {
            'e_dis_id': 16,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Environment Management)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 2,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 17,
            'phase': "In-Sprint Execution",
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 2,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 18,
            'phase': "In-Sprint Design",
            'stlc_name': "In-Sprint Test Design (Regression Maintenance)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 9,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 19,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Functional)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 20,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 20,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 10,
            'override_breakup': 5,
            'status': 1,
        },
        {
            'e_dis_id': 21,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 6,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 22,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Others)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 6,
            'override_breakup': 20,
            'status': 1,
        },
        {
            'e_dis_id': 23,
            'phase': "In-Sprint Execution",
            'stlc_name': "Test Execution (Defect Management)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 3,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 24,
            'phase': "Sprint Review & Retrospection",
            'stlc_name': "Sprint Review & Retrospection",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': 2,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 25,
            'phase': "Sprint Planning",
            'stlc_name': "Sprint Planning & Strategizing",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 1,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 26,
            'phase': "In-Sprint Design",
            'stlc_name': "In Sprint Test Design (Manual)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 15,
            'override_breakup': 15,
            'status': 1,
        },
        {
            'e_dis_id': 27,
            'phase': "In-Sprint Design",
            'stlc_name': "In Sprint Test Design (Automation)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 20,
            'override_breakup': 30,
            'status': 1,
        },
        {
            'e_dis_id': 28,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Environment Management)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 3,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 29,
            'phase': "In-Sprint Execution",
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 3,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 30,
            'phase': "In-Sprint Design",
            'stlc_name': "In-Sprint Test Design (Regression Maintenance)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 13,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 31,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Functional)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 20,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 32,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 12,
            'override_breakup': 5,
            'status': 1,
        },
        {
            'e_dis_id': 33,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 4,
            'override_breakup': 0,
            'status': 1,
        },
        {
            'e_dis_id': 34,
            'phase': "In-Sprint Execution",
            'stlc_name': "In-Sprint Test Execution (Others)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 4,
            'override_breakup': 20,
            'status': 1,
        },
        {
            'e_dis_id': 35,
            'phase': "In-Sprint Execution",
            'stlc_name': "Test Execution (Defect Management)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 4,
            'override_breakup': 10,
            'status': 1,
        },
        {
            'e_dis_id': 36,
            'phase': "Sprint Review & Retrospection",
            'stlc_name': "Sprint Review & Retrospection",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': 1,
            'override_breakup': 0,
            'status': 1,
        },
        
    ]
    for stlc in item:
        cal_inst = Effortsdistribution(
            e_dis_id=stlc['e_dis_id'], 
            phase=stlc['phase'],
            stlc_name=stlc['stlc_name'],
            cat_name=stlc['cat_name'],
            standard_breakup=stlc['standard_breakup'],
            override_breakup=stlc['override_breakup'],
            status=stlc['status'],
        )
        db.session.add(cal_inst)
        db.session.commit()

    # Add data for applicablecognitivesolution

    cogSolData=[
        {
            'sol_id': 1,
            'catelog': "Neuro AI for QA : US to BDD Feature Files Generation",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 20,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 2,
            'catelog': "UI Script Generation Acceleration via GitHub Copilot",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_type': "Predictive AI",
            'solution_category': "External",
            'license_type': "Licensed",
            'licsensing_cost': 19,
            'frequency': "Month",
            'effort_savings': 25,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 3,
            'catelog': "Self-Healing UI automation Scripts",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 4,
            'catelog': "Automation Script Migration",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 5,
            'catelog': "Neuro AI for QA : API Script Generation",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 6,
            'catelog': "Automatic QA Build Failure Analysis",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 3,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 7,
            'catelog': "Intelligent Regression Test Selection",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 20,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 8,
            'catelog': "Quality Insight : Production Ticket Analyzer",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 10,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 9,
            'catelog': "Test strategy / approach generation",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 10,
            'catelog': "Quality Insight : QA Effort Estimation",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 11,
            'catelog': "Application Knowledge Assistant",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 12,
            'catelog': "Domain Knowledge Assistant",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 13,
            'catelog': "Test Automation Assistant",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 14,
            'catelog': "Neuro AI for QA : Automated script generator",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 15,
            'catelog': "Performance Script Migration",
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 16,
            'catelog': "Synthetic Test Data Generation",
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 17,
            'catelog': "Autonomous Test Case Review",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 18,
            'catelog': "Autonomous Test Script Review",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 19,
            'catelog': "Quality Insight : Test Coverage Analysis",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 20,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 20,
            'catelog': "Intelligent Test Prioritization",
            'stlc_name': "Test Execution (Defect Management)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 10,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 21,
            'catelog': "Quality Insight : Defect Root Cause Analyzer",
            'stlc_name': "Test Execution (Defect Management)",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Industrialized",
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 22,
            'catelog': "Assistive Onboarding Bot",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 23,
            'catelog': "Agile Activity Acceleration and Advisory",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 10,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 24,
            'catelog': "Intelligent Analytics Driven Reporting and Governance",
            'stlc_name': "Sprint Review & Retrospection",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        {
            'sol_id': 25,
            'catelog': "Intelligent QA Advisory",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_type': "Predictive AI",
            'solution_category': "Cognizant: Prototype",
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
        },
        
    ]

    for cogsol in cogSolData:
        sol_inst = Applicablecognitivesolutions(
            sol_id=cogsol['sol_id'], 
            catelog=cogsol['catelog'],
            stlc_name=cogsol['stlc_name'],
            solution_category=cogsol['solution_category'],
            solution_type=cogsol['solution_type'],
            license_type=cogsol['license_type'],
            licsensing_cost=cogsol['licsensing_cost'],
            frequency=cogsol['frequency'],
            effort_savings=cogsol['effort_savings'],
            preferred_tool=cogsol['preferred_tool'],
            status=cogsol['status'],
        )
        db.session.add(sol_inst)
        db.session.commit()

    # Add data for phase

    phaseData=[
        {
            'phase_id': 1,
            'phase_name': "Sprint Planning",
            'status': 1,
        },
        {
            'phase_id': 2,
            'phase_name': "In-Sprint Design",
            'status': 1,
        },
        {
            'phase_id': 3,
            'phase_name': "In-Sprint Execution",
            'status': 1,
        },
        {
            'phase_id': 4,
            'phase_name': "Sprint Review & Retrospection",
            'status': 1,
        },
        
    ]

    for phase in phaseData:
        ph_inst = Phase(
            phase_id=phase['phase_id'], 
            phase_name=phase['phase_name'],
            status=phase['status'],
        )
        db.session.add(ph_inst)
        db.session.commit()

    return jsonify({
        "success":True,
        "code":200,
        "message":"Success.",
    }),200