import datetime
# import hashlib
from app import db, app, request, jwt
from flask import Flask, request,jsonify
from flask_jwt_extended import create_access_token, JWTManager, get_jwt_identity, jwt_required, current_user
from sqlalchemy import asc, desc
from extras.utilities import *
from models.Effortsdistribution import *
from sqlalchemy import func
import math
# import shutil


#Default List of all Solution
@app.route("/default/solution/add",methods=["POST"])
def insert_default_solution(email):
    default_solutions=[
        {
            'catelog': "UI Script Generation Acceleration via GitHub Copilot",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_category': "External",
            'solution_type': "Generative AI",            
            'license_type': "Licensed",
            'licsensing_cost': 19,
            'frequency': "Month",
            'effort_savings': 25,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Microsoft GitHub CoPilot is a code assist platform which can aid in converting user stories into BDD feature files and also accelerate UI script development in Java, JavaScript or Python based test automation frameworks (Selenium, Cypress, Python Robot etc.) through code generation prompts',
            'adoption_per':80,
        },
        {
            'catelog': "Automation Script Migration",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_category': "Cognizant: Prototype",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'GenAI based solution which can help in automation testing framework or codebase migration from one solution (Ex. Selenium, Cypress etc.) to another (Ex. WebDriver IO, Python Robot etc.).',
            'adoption_per':30,
        },
        {
            'catelog': "Neuro AI for QA : API Script Generation",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Gen AI based solution integrated with client specific foundational models (LLM) such as GPT 3.5, Llama etc. - which can accept API end-points, service specifications or Swagger details as inputs and create service test automation scripts following client specific framework.',
            'adoption_per':30,
        },
        {
            'catelog': "Automated QA Build Failure Analysis",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Predictive AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 3,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Predictive AI based solution trained with test logs executed in Jenkins or other CI/CT solutions and corresponding root cuases of failures (such as script issue, data issue, environment issue, code issue etc.) - so that any future test script failure in the CI/CT pipeline can be automatically analyzed and the root cause can be assigned to the same.',
            'adoption_per':50,
        },
        {
            'catelog': "Intelligent Regression Test Selection",
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Predictive AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 20,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'AI based solution trained with historical defects, regression test logs and impacted application modules to perform trend analysis and identify the right set of regression test cases for a specific release based on the application modules undergoing functional changes.',
            'adoption_per':70,
        },
        {
            'catelog': "Quality Insight : Production Ticket Analyzer",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Predictive AI",            
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 10,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Predictive AI based solution trained with historical production tickets and corresponding root causes as well as impacted application modules - so that insights can be derived to identify the defect hotspots and also root cause can be automatically predicted for any production incident in future.',
            'adoption_per':30,
        },
        {
            'catelog': "Quality Insight : QA Effort Estimation",
            'stlc_name': "Sprint Planning & Strategizing",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Predictive AI",            
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Predictive AI based solution trained with historical user stories and corresponding effort sizes (story points) - so that any user story part of an upcoming sprint backlog can be automatically analyzed and corresponding story size can be assigned against the same.',
            'adoption_per':50,
        },
        {
            'catelog': "Application Knowledge Assistant",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Gen AI based knowledge management solution infused with application specific workflows, business processes, user journeys etc. - so that any application related question can be asked to the chatbot for finding clarifications.',
            'adoption_per':80,
        },
        {
            'catelog': "Domain Knowledge Assistant",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Gen AI based knowledge management solution infused with domain (Life Insurance, Annuities, Long Term Care, Property & Casualty etc.) specific business process scenarios such as new business, underwriting, claims etc. - so that any domain or business process related question can be asked to the chatbot for finding clarifications.',
            'adoption_per':80,
        },
        {
            'catelog': "Neuro AI for QA : Automated script generator",
            'stlc_name': "In Sprint Test Design (Automation)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Gen AI based solution integrated with client specific foundational models (LLM) such as GPT 3.5, Llama etc. - which can accept manual test cases as inputs and convert them into Selenium based UI automation scripts following client specific framework.',
            'adoption_per':80,
        },
        {
            'catelog': "Performance Script Migration",
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'solution_category': "Cognizant: Prototype",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 15,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'GenAI based solution which can help in performance testing framework or codebase migration from one solution (Ex. LonadRunner etc.) to another (Ex. JMeter etc.).',
            'adoption_per':30,
        },
        {
            'catelog': "Synthetic Test Data Generation",
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'solution_category': "Cognizant: Prototype",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Generative AI based solution which can be infused with application scenario specific test data details to share the different combinations and types of test data to use for different functional test cases.',
            'adoption_per':70,
        },
        {
            'catelog': "Intelligent Test Prioritization",
            'stlc_name': "In-Sprint Test Execution (Defect Management)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Predictive AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 10,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'AI based solution trained with historical test logs, defects and Production incidents to perform trend analysis and prioritize the functional test cases for execution cycles to identify the Sev1/Sev2 defects in early phase of testing.',
            'adoption_per':70,
        },
        {
            'catelog': "Quality Insight : Defect Root Cause Analyzer",
            'stlc_name': "In-Sprint Test Execution (Others)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Predictive AI",            
            'license_type': "Licensed",
            'licsensing_cost': 30,
            'frequency': "Month",
            'effort_savings': 5,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Predictive AI based solution trained with historical defect logs and corresponding root causes - so that any new defect log can be automatically analyzed and the root cause can be assigned against the same, thereby minimizing the need for defect triage.',
            'adoption_per':80,
        },
        {
            'catelog': "Neuro AI for QA : US to BDD Feature Files Generation",
            'stlc_name': "In Sprint Test Design (Manual)",
            'solution_category': "Cognizant: Industrialized",
            'solution_type': "Generative AI",            
            'license_type': "Free",
            'licsensing_cost': 0,
            'frequency': "Month",
            'effort_savings': 20,
            'preferred_tool': "Y",
            'status': 1,
            'short_desc':'Gen AI based solution integrated with client specific foundational models (LLM) such as GPT 3.5, Llama etc. - which can accept user stories or business requirements as inputs and convert them into BDD feature files in Gherkins format - thereby supporting Agile projects running Behaviour Driven Development (BDD).',
            'adoption_per':50,
        },
        
    ]

    for defaultSol in default_solutions:
        sol_inst = Applicablecognitivesolutions(
            catelog=defaultSol['catelog'],
            stlc_name=defaultSol['stlc_name'],
            solution_category=defaultSol['solution_category'],
            solution_type=defaultSol['solution_type'],
            license_type=defaultSol['license_type'],
            licsensing_cost=defaultSol['licsensing_cost'],
            frequency=defaultSol['frequency'],
            effort_savings=defaultSol['effort_savings'],
            preferred_tool=defaultSol['preferred_tool'],
            status=defaultSol['status'],
            short_desc=defaultSol['short_desc'],
            adoption_per=defaultSol['adoption_per'],
            added_by=email,
        )
        db.session.add(sol_inst)
        db.session.commit()

    return jsonify({
        "success":True,
        "code":200,
        "message":"Success.",
    }),200


#Default List of all Efforts
@app.route("/default/effort/add",methods=["POST"])
def insert_default_effort(email):
    default_efforts=[
        {
            'phase': 1,
            'stlc_name': "Sprint Planning & Strategizing",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "5",            
            'override_breakup': "5",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In Sprint Test Design (Manual)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "15",            
            'override_breakup': "15",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In Sprint Test Design (Automation)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "30",            
            'override_breakup': "30",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Environment Management)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "2",            
            'override_breakup': "2",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "2",            
            'override_breakup': "2",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In-Sprint Test Design (Regression Maintenance)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "5",            
            'override_breakup': "5",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Functional)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "21",            
            'override_breakup': "21",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "5",            
            'override_breakup': "5",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "5",            
            'override_breakup': "5",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Others)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "5",            
            'override_breakup': "5",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Defect Management)",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "3",            
            'override_breakup': "3",
            'status': 1,
        },
        {
            'phase': 4,
            'stlc_name': "Sprint Review & Retrospection",
            'cat_name': "Greenfield Digital Transformation",
            'standard_breakup': "2",            
            'override_breakup': "2",
            'status': 1,
        },
        {
            'phase': 1,
            'stlc_name': "Sprint Planning & Strategizing",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "3",            
            'override_breakup': "3",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In Sprint Test Design (Manual)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "15",            
            'override_breakup': "15",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In Sprint Test Design (Automation)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "22",            
            'override_breakup': "22",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Environment Management)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "2",            
            'override_breakup': "2",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "2",            
            'override_breakup': "2",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In-Sprint Test Design (Regression Maintenance)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "9",            
            'override_breakup': "9",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Functional)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "20",            
            'override_breakup': "20",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "10",            
            'override_breakup': "10",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "6",            
            'override_breakup': "6",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Others)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "6",            
            'override_breakup': "6",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Defect Management)",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "3",            
            'override_breakup': "3",
            'status': 1,
        },
        {
            'phase': 4,
            'stlc_name': "Sprint Review & Retrospection",
            'cat_name': "Platform Upgrade and Modernization",
            'standard_breakup': "2",            
            'override_breakup': "2",
            'status': 1,
        },
        {
            'phase': 1,
            'stlc_name': "Sprint Planning & Strategizing",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "1",            
            'override_breakup': "1",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In Sprint Test Design (Manual)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "15",            
            'override_breakup': "15",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In Sprint Test Design (Automation)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "20",            
            'override_breakup': "20",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Environment Management)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "3",            
            'override_breakup': "3",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In Sprint Test Execution (Test Data)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "3",            
            'override_breakup': "3",
            'status': 1,
        },
        {
            'phase': 2,
            'stlc_name': "In-Sprint Test Design (Regression Maintenance)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "13",            
            'override_breakup': "13",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Functional)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "20",            
            'override_breakup': "20",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Regression)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "12",            
            'override_breakup': "12",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (NFT)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "4",            
            'override_breakup': "4",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Others)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "4",            
            'override_breakup': "4",
            'status': 1,
        },
        {
            'phase': 3,
            'stlc_name': "In-Sprint Test Execution (Defect Management)",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "4",            
            'override_breakup': "4",
            'status': 1,
        },
        {
            'phase': 4,
            'stlc_name': "Sprint Review & Retrospection",
            'cat_name': "Break-fix, Maintenance, Enhancements",
            'standard_breakup': "1",            
            'override_breakup': "1",
            'status': 1,
        },        
    ]

    for defaultEff in default_efforts:
        eff_inst = Effortsdistribution(
            phase=defaultEff['phase'],
            stlc_name=defaultEff['stlc_name'],
            cat_name=defaultEff['cat_name'],
            standard_breakup=defaultEff['standard_breakup'],
            override_breakup=defaultEff['override_breakup'],
            status=defaultEff['status'],
            added_by=email,
        )
        db.session.add(eff_inst)
        db.session.commit()

    return jsonify({
        "success":True,
        "code":200,
        "message":"Success.",
    }),200